import random
from toontown.battle.BattleBase import *
from direct.directnotify import DirectNotifyGlobal
from otp.otpbase import OTPLocalizer
from toontown.toonbase import TTLocalizer
notify = DirectNotifyGlobal.directNotify.newCategory('SuitBattleGlobals')
debugAttackSequence = {}

def pickFromFreqList(freqList):
    randNum = random.randint(0, 99)
    count = 0
    index = 0
    level = None
    for f in freqList:
        count = count + f
        if randNum < count:
            level = index
            break
        index = index + 1

    return level


def getActualFromRelativeLevel(name, relLevel):
    data = SuitAttributes[name]
    actualLevel = data['level'] + relLevel
    return actualLevel


def getSuitVitals(name, level = -1):
    data = SuitAttributes[name]
    if level == -1:
        level = pickFromFreqList(data['freq'])
    dict = {}
    dict['level'] = getActualFromRelativeLevel(name, level)
    if dict['level'] == 11:
        level = 0
    dict['hp'] = data['hp'][level]
    dict['def'] = data['def'][level]
    attacks = data['attacks']
    alist = []
    for a in attacks:
        adict = {}
        name = a[0]
        adict['name'] = name
        adict['animName'] = SuitAttacks[name][0]
        adict['hp'] = a[1][level]
        adict['acc'] = a[2][level]
        adict['freq'] = a[3][level]
        adict['group'] = SuitAttacks[name][1]
        alist.append(adict)

    dict['attacks'] = alist
    return dict


def pickSuitAttack(attacks, suitLevel):
    attackNum = None
    randNum = random.randint(0, 99)
    notify.debug('pickSuitAttack: rolled %d' % randNum)
    count = 0
    index = 0
    total = 0
    for c in attacks:
        total = total + c[3][suitLevel]

    for c in attacks:
        count = count + c[3][suitLevel]
        if randNum < count:
            attackNum = index
            notify.debug('picking attack %d' % attackNum)
            break
        index = index + 1

    configAttackName = simbase.config.GetString('attack-type', 'random')
    if configAttackName == 'random':
        return attackNum
    elif configAttackName == 'sequence':
        for i in xrange(len(attacks)):
            if  attacks[i] not in debugAttackSequence:
                debugAttackSequence[attacks[i]] = 1
                return i

        return attackNum
    else:
        for i in xrange(len(attacks)):
            if attacks[i][0] == configAttackName:
                return i

        return attackNum
    return


def getSuitAttack(suitName, suitLevel, attackNum = -1):
    attackChoices = SuitAttributes[suitName]['attacks']
    if attackNum == -1:
        notify.debug('getSuitAttack: picking attacking for %s' % suitName)
        attackNum = pickSuitAttack(attackChoices, suitLevel)
    attack = attackChoices[attackNum]
    adict = {}
    adict['suitName'] = suitName
    name = attack[0]
    adict['name'] = name
    adict['id'] = SuitAttacks.keys().index(name)
    adict['animName'] = SuitAttacks[name][0]
    adict['hp'] = attack[1][suitLevel]
    adict['acc'] = attack[2][suitLevel]
    adict['freq'] = attack[3][suitLevel]
    adict['group'] = SuitAttacks[name][1]
    return adict


SuitAttributes = {'f': {'name': TTLocalizer.SuitFlunky,
       'singularname': TTLocalizer.SuitFlunkyS,
       'pluralname': TTLocalizer.SuitFlunkyP,
       'level': 0,
       'hp': (10,
              20,
              30,
              40,
              50),
       'def': (2,
               5,
               10,
               12,
               15),
       'freq': (50,
                30,
                10,
                5,
                5),
       'acc': (35,
               40,
               45,
               50,
               55),
       'attacks': (('PoundKey',
                    (4,
                     6,
                     8,
                     10,
                     12),
                    (75,
                     75,
                     80,
                     80,
                     90),
                    (15,
                     15,
                     15,
                     15,
                     15)), 
				   ('Chomp',
                    (3,
                     5,
                     7,
                     8,
                     9),
                    (50,
                     55,
                     60,
                     65,
                     70),
                    (30,
                     30,
                     30,
                     30,
                     30)),
                   ('Shred',
                    (5,
                     7,
                     9,
                     11,
                     13),
                    (50,
                     55,
                     60,
                     65,
                     70),
                    (40,
                     40,
                     40,
                     40,
                     40)), 					 
				   ('Bite',
                    (1,
                     2,
                     3,
                     4,
                     5),
                    (75,
                     80,
                     85,
                     90,
                     95),
                    (60,
                     50,
                     40,
                     30,
                     20)))},
 'p': {'name': TTLocalizer.SuitPencilPusher,
       'singularname': TTLocalizer.SuitPencilPusherS,
       'pluralname': TTLocalizer.SuitPencilPusherP,
       'level': 1,
       'hp': (20,
              30,
              40,
              50,
              65),
       'def': (5,
               10,
               15,
               20,
               25),
       'freq': (50,
                30,
                10,
                5,
                5),
       'acc': (45,
               50,
               55,
               60,
               65),
       'attacks': (('ReOrg',
                    (2,
                     3,
                     4,
                     6,
                     9),
                    (75,
                     75,
                     75,
                     75,
                     75),
                    (20,
                     20,
                     20,
                     20,
                     20)),
                   ('RubOut',
                    (5,
                     7,
                     9,
                     12,
                     15),
                    (75,
                     75,
                     75,
                     75,
                     75),
                    (20,
                     20,
                     20,
                     20,
                     20)),
                   ('FingerWag',
                    (2,
                     3,
                     4,
                     5,
                     6),
                    (75,
                     75,
                     75,
                     75,
                     75),
                    (35,
                     30,
                     25,
                     20,
                     15)),
                   ('FillWithLead',
                    (5,
                     7,
                     9,
                     12,
                     15),
                    (75,
                     75,
                     75,
                     75,
                     75),
                    (5,
                     10,
                     15,
                     20,
                     25)),
                   ('WriteOff',
                    (3,
                     5,
                     7,
                     9,
                     11),
                    (75,
                     75,
                     75,
                     75,
                     75),
                    (20,
                     20,
                     20,
                     20,
                     20)))},
 'ym': {'name': TTLocalizer.SuitYesman,
        'singularname': TTLocalizer.SuitYesmanS,
        'pluralname': TTLocalizer.SuitYesmanP,
        'level': 2,
        'hp': (30,
               40,
               50,
               65,
               80),
        'def': (10,
                15,
                20,
                25,
                30),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (65,
                70,
                75,
                80,
                85),
        'attacks': (('PowerTrip',
                     (4,
                      6,
                      8,
                      10,
                      12),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (20,
                      20,
                      20,
                      20,
                      20)),
					('CigarSmoke',
                     (5,
                      8,
                      11,
                      14,
                      17),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('RazzleDazzle',
                     (5,
                      7,
                      9,
                      12,
                      15),
                     (80,
                      80,
                      80,
                      80,
                      80),
                     (25,
                      25,
                      25,
                      25,
                      25)),
                    ('Synergy',
                     (9,
                      11,
                      13,
                      15,
                      18),
                     (50,
                      60,
                      70,
                      80,
                      90),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('ParadigmShift',
                     (3,
                      6,
                      9,
                      12,
                      15),
                     (50,
                      60,
                      70,
                      80,
                      90),
                     (20,
                      20,
                      20,
                      20,
                      20)))},
 'mm': {'name': TTLocalizer.SuitMicromanager,
        'singularname': TTLocalizer.SuitMicromanagerS,
        'pluralname': TTLocalizer.SuitMicromanagerP,
        'level': 3,
        'hp': (40,
               50,
               65,
               80,
               100),
        'def': (15,
                20,
                25,
                30,
                35),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (70,
                75,
                80,
                82,
                85),
        'attacks': (('Quake',
                     (11,
                      14,
                      17,
                      20,
                      23),
                     (50,
                      60,
                      70,
                      80,
                      90),
                     (30,
                      30,
                      30,
                      30,
                      30)),
					('PowerTrip',
                     (11,
                      13,
                      15,
                      17,
                      19),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (35,
                      35,
                      35,
                      35,
                      35)),
                    ('FingerWag',
                     (6,
                      9,
                      12,
                      15,
                      18),
                     (50,
                      60,
                      70,
                      80,
                      90),
                     (10,
                      10,
                      10,
                      10,
                      10)),
                    ('Tremor',
                     (4,
                      6,
                      8,
                      10,
                      12),
                     (50,
                      60,
                      70,
                      80,
                      90),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('BrainStorm',
                     (6,
                      9,
                      12,
                      15,
                      18),
                     (50,
                      50,
                      50,
                      50,
                      50),
                     (25,
                      25,
                      25,
                      25,
                      25)),
                    ('Shake',
                     (6,
                      9,
                      12,
                      15,
                      18),
                     (50,
                      60,
                      70,
                      80,
                      90),
                     (20,
                      20,
                      20,
                      20,
                      20)))},
 'ds': {'name': TTLocalizer.SuitDownsizer,
        'singularname': TTLocalizer.SuitDownsizerS,
        'pluralname': TTLocalizer.SuitDownsizerP,
        'level': 4,
        'hp': (50,
               65,
               80,
               100,
               125),
        'def': (20,
                25,
                30,
                35,
                40),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (35,
                40,
                45,
                50,
                55),
        'attacks': (('Canned',
                     (7,
                      9,
                      12,
                      15,
                      18),
                     (60,
                      75,
                      80,
                      85,
                      90),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('Withdrawal',
                     (6,
                      9,
                      12,
                      15,
                      18),
                     (50,
                      65,
                      70,
                      75,
                      80),
                     (20,
                      20,
                      20,
                      20,
                      20)),
					('GuiltTrip',
                     (10,
                      12,
                      15,
                      18,
                      20),
                     (50,
                      65,
                      70,
                      75,
                      80),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('PinkSlip',
                     (11,
                      13,
                      15,
                      17,
                      19),
                     (60,
                      65,
                      75,
                      80,
                      85),
                     (25,
                      25,
                      25,
                      25,
                      25)),
                    ('Sacked',
                     (8,
                      11,
                      14,
                      17,
                      20),
                     (50,
                      50,
                      50,
                      50,
                      50),
                     (15,
                      15,
                      15,
                      15,
                      15)))},
 'hh': {'name': TTLocalizer.SuitHeadHunter,
        'singularname': TTLocalizer.SuitHeadHunterS,
        'pluralname': TTLocalizer.SuitHeadHunterP,
        'level': 5,
        'hp': (65,
               80,
               100,
               125,
               150),
        'def': (25,
                30,
                35,
                40,
                45),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (35,
                40,
                45,
                50,
                55),
        'attacks': (('Quake',
                     (13,
                      15,
                      17,
                      19,
                      21),
                     (60,
                      75,
                      80,
                      85,
                      90),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('BrainStorm',
                     (12,
                      14,
                      16,
                      18,
                      20),
                     (50,
                      60,
                      70,
                      80,
                      90),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('FingerWag',
                     (11,
                      13,
                      15,
                      17,
                      19),
                     (60,
                      65,
                      70,
                      75,
                      80),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('Fired',
                     (12,
                      15,
                      18,
                      21,
                      24),
                     (65,
                      75,
                      80,
                      85,
                      95),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('BuzzWord',
                     (9,
                      11,
                      13,
                      15,
                      17),
                     (65,
                      75,
                      80,
                      85,
                      90),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('Chomp',
                     (14,
                      16,
                      18,
                      20,
                      21),
                     (60,
                      65,
                      70,
                      75,
                      80),
                     (10,
                      10,
                      10,
                      10,
                      10)))},
 'cr': {'name': TTLocalizer.SuitCorporateRaider,
        'singularname': TTLocalizer.SuitCorporateRaiderS,
        'pluralname': TTLocalizer.SuitCorporateRaiderP,
        'level': 6,
        'hp': (80,
               100,
               125,
               150,
               185),
        'def': (30,
                35,
                40,
                45,
                50),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (35,
                40,
                45,
                50,
                55),
        'attacks': (('Canned',
                     (10,
                      12,
                      14,
                      16,
                      18),
                     (60,
                      75,
                      80,
                      85,
                      90),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('Withdrawal',
                     (15,
                      18,
                      21,
                      24,
                      27),
                     (60,
                      70,
                      75,
                      80,
                      90),
                     (35,
                      35,
                      35,
                      35,
                      35)),
                    ('HalfWindsor',
                     (10,
                      13,
                      16,
                      19,
                      22),
                     (60,
                      65,
                      70,
                      75,
                      80),
                     (30,
                      30,
                      30,
                      30,
                      30)),
                    ('PickPocket',
                     (10,
                      12,
                      14,
                      16,
                      18),
                     (65,
                      75,
                      80,
                      85,
                      95),
                     (15,
                      15,
                      15,
                      15,
                      15)))},
 'tbc': {'name': TTLocalizer.SuitTheBigCheese,
         'singularname': TTLocalizer.SuitTheBigCheeseS,
         'pluralname': TTLocalizer.SuitTheBigCheeseP,
         'level': 7,
         'hp': (100,
                125,
                150,
                185,
				235,
				300,
				400,
				500,
				600,
				700,
				800,
				900,
                1000),
         'def': (35,
                 40,
                 45,
                 55,
				 50,
				 50,
				 50,
				 50,
				 50,
				 50,
				 50,
				 50,
                 50),
         'freq': (50,
                  30,
                  10,
				  10,
				  10,
				  10,
				  10,
				  10,
				  10,
				  10,
				  10,
                  10,
                  5),
         'acc': (35,
                 40,
                 45,
                 50,
				 50,
				 50,
				 50,
				 50,
				 50,
				 50,
				 50,
				 50,
                 50),
         'attacks': (('CigarSmoke',
                      (13,
                       17,
                       21,
                       25,
					   29,
					   32,
					   35,
					   38,
					   40,
					   42,
					   44,
					   46,
                       42),
                      (55,
                       65,
                       75,
                       85,
					   90,
					   90,
					   90,
					   90,
					   90,
					   90,
					   90,
					   90,
                       95),
                      (20,
                       20,
                       20,
                       20,
					   20,
					   20,
					   20,
					   20,
					   20,
					   20,
					   20,
					   20,
                       20)),
                     ('EvilEye',
                      (14,
                       17,
                       20,
                       23,
					   27,
					   30,
					   33,
					   36,
					   38,
					   40,
					   42,
					   44,
                       46),
                      (70,
                       75,
                       85,
                       90,
					   90,
					   90,
					   90,
					   90,
					   90,
					   90,
					   90,
					   90,
                       95),
                      (10,
                       10,
                       10,
					   10,
					   10,
					   10,
					   10,
					   10,
					   10,
					   10,
					   10,
                       10,
                       10)),
                     ('PowerTrip',
                      (19,
                       22,
                       25,
                       28,
					   31,
					   33,
					   35,
					   37,
					   39,
					   40,
					   42,
					   43,
                       44),
                      (60,
                       65,
                       70,
					   70,
					   70,
					   70,
					   70,
					   70,
					   70,
					   70,
					   70,
                       75,
                       80),
                      (20,
                       20,
                       20,
					   20,
					   20,
					   20,
					   20,
					   20,
					   20,
					   20,
					   20,
                       20,
                       20)),
                     ('SongAndDance',
                      (10,
                       15,
                       20,
                       25,
					   30,
					   34,
					   37,
					   40,
					   42,
					   44,
					   45,
					   46,
                       47),
                      (55,
                       65,
                       70,
                       75,
					   75,
					   75,
					   75,
					   75,
					   75,
					   75,
					   75,
					   75,
                       80),
                      (50,
                       50,
                       50,
					   50,
					   50,
					   50,
					   50,
					   50,
					   50,
					   50,
					   50,
                       50,
                       50)))},
 'cc': {'name': TTLocalizer.SuitColdCaller,
        'singularname': TTLocalizer.SuitColdCallerS,
        'pluralname': TTLocalizer.SuitColdCallerP,
        'level': 0,
        'hp': (10,
               20,
               30,
               40,
               50),
        'def': (2,
                5,
                10,
                12,
                15),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (35,
                40,
                45,
                50,
                55),
        'attacks': (('Schmooze',
                     (4,
                      6,
                      9,
                      12,
                      15),
                     (90,
                      90,
                      90,
                      90,
                      90),
                     (30,
                      30,
                      30,
                      30,
                      30)),
                    ('ParadigmShift',
                     (2,
                      4,
                      6,
                      8,
                      10),
                     (75,
                      80,
                      85,
                      90,
                      95),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('HotAir',
                     (1,
                      2,
                      3,
                      4,
                      5),
                     (50,
                      55,
                      60,
                      65,
                      70),
                     (40,
                      40,
                      40,
                      40,
                      40)),
                    ('DoubleTalk',
                     (4,
                      6,
                      8,
                      10,
                      12),
                     (70,
                      70,
                      70,
                      70,
                      70),
                     (15,
                      15,
                      15,
                      15,
                      15)))},
 'tm': {'name': TTLocalizer.SuitTelemarketer,
        'singularname': TTLocalizer.SuitTelemarketerS,
        'pluralname': TTLocalizer.SuitTelemarketerP,
        'level': 1,
        'hp': (20,
               30,
               40,
               50,
               65),
        'def': (5,
                10,
                15,
                20,
                25),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (45,
                50,
                55,
                60,
                65),
        'attacks': (('PoundKey',
                     (4,
                      6,
                      8,
                      10,
                      12),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (15,
                      15,
                      15,
                      15,
                      15)),
					('DoubleTalk',
                     (7,
                      9,
                      11,
                      13,
                      16),
                     (50,
                      65,
                      70,
                      75,
                      80),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('Schmooze',
                     (5,
                      7,
                      9,
                      11,
                      13),
                     (70,
                      70,
                      70,
                      70,
                      70),
                     (30,
                      30,
                      30,
                      30,
                      30)),
                    ('PickPocket',
                     (2,
                      3,
                      4,
                      5,
                      6),
                     (75,
                      80,
                      85,
                      90,
                      95),
                     (40,
                      40,
                      40,
                      40,
                      40)))},
 'nd': {'name': TTLocalizer.SuitNameDropper,
        'singularname': TTLocalizer.SuitNameDropperS,
        'pluralname': TTLocalizer.SuitNameDropperP,
        'level': 2,
        'hp': (30,
               40,
               50,
               65,
               80),
        'def': (10,
                15,
                20,
                25,
                30),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (65,
                70,
                75,
                80,
                85),
        'attacks': (('PowerTrip',
                     (5,
                      7,
                      9,
                      12,
                      15),
                     (95,
                      95,
                      95,
                      95,
                      95),
                     (40,
                      40,
                      40,
                      40,
                      40)),
					('Fired',
                     (4,
                      6,
                      8,
                      10,
                      12),
                     (50,
                      65,
                      70,
                      75,
                      80),
                     (30,
                      30,
                      30,
                      30,
                      30)),
                    ('ParadigmShift',
                     (3,
                      5,
                      8,
                      11,
                      14),
                     (90,
                      90,
                      90,
                      90,
                      90),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('RazzleDazzle',
                     (7,
                      10,
                      13,
                      16,
                      19),
                     (95,
                      95,
                      95,
                      95,
                      95),
                     (15,
                      15,
                      15,
                      15,
                      15)))},
 'gh': {'name': TTLocalizer.SuitGladHander,
        'singularname': TTLocalizer.SuitGladHanderS,
        'pluralname': TTLocalizer.SuitGladHanderP,
        'level': 3,
        'hp': (40,
               50,
               65,
               80,
               100),
        'def': (15,
                20,
                25,
                30,
                35),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (70,
                75,
                80,
                82,
                85),
        'attacks': (('Schmooze',
                     (9,
                      13,
                      17,
                      21,
                      25),
                     (50,
                      65,
                      70,
                      75,
                      80),
                     (15,
                      15,
                      15,
                      15,
                      15)),
					('ParadigmShift',
                     (6,
                      8,
                      10,
                      12,
                      14),
                     (50,
                      65,
                      70,
                      75,
                      80),
                     (30,
                      30,
                      30,
                      30,
                      30)),
				    ('Rolodex',
                     (8,
                      9,
                      11,
                      14,
                      17),
                     (50,
                      65,
                      70,
                      75,
                      80),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('DoubleTalk',
                     (7,
                      9,
                      11,
                      13,
                      16),
                     (30,
                      40,
                      50,
                      60,
                      70),
                     (40,
                      40,
                      40,
                      40,
                      40)))},
 'ms': {'name': TTLocalizer.SuitMoverShaker,
        'singularname': TTLocalizer.SuitMoverShakerS,
        'pluralname': TTLocalizer.SuitMoverShakerP,
        'level': 4,
        'hp': (50,
               65,
               80,
               100,
               125),
        'def': (20,
                25,
                30,
                35,
                40),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (35,
                40,
                45,
                50,
                55),
        'attacks': (('SongAndDance',
                     (10,
                      12,
                      14,
                      16,
                      18),
                     (60,
                      75,
                      80,
                      85,
                      90),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('ClipOnTie',
                     (11,
                      14,
                      17,
                      20,
                      24),
                     (50,
                      65,
                      70,
                      75,
                      80),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('RazzleDazzle',
                     (14,
                      16,
                      18,
                      20,
                      22),
                     (60,
                      65,
                      75,
                      80,
                      85),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('PeckingOrder',
                     (11,
                      13,
                      15,
                      17,
                      20),
                     (70,
                      75,
                      80,
                      85,
                      90),
                     (25,
                      25,
                      25,
                      25,
                      25)),
                    ('HangUp',
                     (9,
                      10,
                      11,
                      12,
                      13),
                     (50,
                      50,
                      50,
                      50,
                      50),
                     (20,
                      20,
                      20,
                      20,
                      20)))},
 'tf': {'name': TTLocalizer.SuitTwoFace,
        'singularname': TTLocalizer.SuitTwoFaceS,
        'pluralname': TTLocalizer.SuitTwoFaceP,
        'level': 5,
        'hp': (65,
               80,
               100,
               125,
               150),
        'def': (25,
                30,
                35,
                40,
                45),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (35,
                40,
                45,
                50,
                55),
        'attacks': (('RazzleDazzle',
                     (9,
                      12,
                      15,
                      18,
                      21),
                     (60,
                      75,
                      80,
                      85,
                      90),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('PoundKey',
                     (7,
                      10,
                      12,
                      14,
                      17),
                     (50,
                      60,
                      70,
                      80,
                      90),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('PowerTrip',
                     (10,
                      12,
                      15,
                      18,
                      20),
                     (60,
                      65,
                      70,
                      75,
                      80),
                     (25,
                      25,
                      25,
                      25,
                      25)),
					('Synergy',
                     (12,
                      15,
                      18,
                      21,
                      24),
                     (50,
                      65,
                      70,
                      75,
                      80),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('Spin',
                     (7,
                      9,
                      11,
                      13,
                      15),
                     (65,
                      75,
                      80,
                      85,
                      90),
                     (20,
                      20,
                      20,
                      20,
                      20)))},
 'm': {'name': TTLocalizer.SuitTheMingler,
       'singularname': TTLocalizer.SuitTheMinglerS,
       'pluralname': TTLocalizer.SuitTheMinglerP,
       'level': 6,
       'hp': (80,
              100,
              125,
              150,
              185),
       'def': (30,
               35,
               40,
               45,
               50),
       'freq': (50,
                30,
                10,
                5,
                5),
       'acc': (35,
               40,
               45,
               50,
               55),
       'attacks': (('Schmooze',
                    (10,
                     12,
                     14,
                     16,
                     18),
                    (60,
                     75,
                     80,
                     85,
                     90),
                    (20,
                     20,
                     20,
                     20,
                     20)),
                   ('ParadigmShift',
                    (15,
                     18,
                     21,
                     25,
                     29),
                    (60,
                     70,
                     75,
                     80,
                     90),
                    (20,
                     20,
                     20,
                     20,
                     20)),
                   ('PowerTrip',
                    (12,
                     15,
                     18,
                     21,
                     24),
                    (60,
                     65,
                     70,
                     75,
                     80),
                    (15,
                     15,
                     15,
                     15,
                     15)),
                   ('RedTape',
                    (12,
                     13,
                     15,
                     18,
                     20),
                    (55,
                     65,
                     75,
                     85,
                     95),
                    (20,
                     20,
                     20,
                     20,
                     20)),
                   ('EvictionNotice',
                    (14,
                     16,
                     18,
                     20,
                     22),
                    (55,
                     65,
                     75,
                     85,
                     95),
                    (15,
                     15,
                     15,
                     15,
                     15)),
                   ('RazzleDazzle',
                    (17,
                     18,
                     19,
                     20,
                     21),
                    (70,
                     75,
                     80,
                     85,
                     95),
                    (10,
                     10,
                     10,
                     10,
                     10)))},
 'mh': {'name': TTLocalizer.SuitMrHollywood,
        'singularname': TTLocalizer.SuitMrHollywoodS,
        'pluralname': TTLocalizer.SuitMrHollywoodP,
        'level': 7,
        'hp': (100,
               125,
               150,
               185,
			   235,
			   300,
			   400,
               500),
        'def': (35,
                40,
                45,
                55,
				50,
				50,
				50,
                50),
        'freq': (50,
                 30,
                 10,
				 10,
				 10,
				 10,
                 10,
                 5),
        'acc': (35,
                40,
                45,
				50,
				50,
				50,
                50,
                50),
        'attacks': (('PowerTrip',
                     (18,
                      21,
                      24,
                      27,
					  30,
					  32,
					  34,
                      36),
                     (55,
                      65,
                      75,
                      85,
					  85,
					  85,
					  85,
                      95),
                     (50,
                      50,
                      50,
					  50,
					  50,
					  50,
                      50,
                      50)),
					('SongAndDance',
                     (16,
                      18,
                      20,
                      22,
					  24,
					  26,
					  28,
                      30),
                     (50,
                      65,
                      70,
                      75,
					  75,
					  75,
					  75,
                      80),
                     (35,
                      35,
                      35,
                      35,
					  35,
					  35,
					  35,
                      35)),
				    ('RazzleDazzle',
                     (16,
                      19,
                      22,
                      25,
					  28,
					  30,
					  32,
                      34),
                     (50,
                      65,
                      70,
					  70,
					  70,
					  70,
                      75,
                      80),
                     (35,
                      35,
                      35,
					  35,
					  35,
					  35,
                      35,
                      35)))},
 'sc': {'name': TTLocalizer.SuitShortChange,
        'singularname': TTLocalizer.SuitShortChangeS,
        'pluralname': TTLocalizer.SuitShortChangeP,
        'level': 0,
        'hp': (10,
               20,
               30,
               40,
               50),
        'def': (2,
                5,
                10,
                12,
                15),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (35,
                40,
                45,
                50,
                55),
        'attacks': (('Watercooler',
                     (4,
                      6,
                      8,
                      10,
                      12),
                     (50,
                      50,
                      50,
                      50,
                      50),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('BounceCheck',
                     (5,
                      7,
                      9,
                      12,
                      15),
                     (75,
                      80,
                      85,
                      90,
                      95),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('ClipOnTie',
                     (1,
                      2,
                      3,
                      4,
                      5),
                     (50,
                      50,
                      50,
                      50,
                      50),
                     (25,
                      25,
                      25,
                      25,
                      25)),
                    ('PickPocket',
                     (4,
                      6,
                      8,
                      10,
                      12),
                     (95,
                      95,
                      95,
                      95,
                      95),
                     (40,
                      40,
                      40,
                      40,
                      40)))},
 'pp': {'name': TTLocalizer.SuitPennyPincher,
        'singularname': TTLocalizer.SuitPennyPincherS,
        'pluralname': TTLocalizer.SuitPennyPincherP,
        'level': 1,
        'hp': (20,
               30,
               40,
               50,
               65),
        'def': (5,
                10,
                15,
                20,
                25),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (45,
                50,
                55,
                60,
                65),
        'attacks': (('BounceCheck',
                     (6,
                      9,
                      12,
                      15,
                      18),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (45,
                      45,
                      45,
                      45,
                      45)), ('BrainStorm',
                     (4,
                      6,
                      8,
                      10,
                      12),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (20,
                      20,
                      20,
                      20,
                      20)), ('FingerWag',
                     (3,
                      4,
                      5,
                      7,
                      9),
                     (50,
                      50,
                      50,
                      50,
                      50),
                     (35,
                      35,
                      35,
                      35,
                      35)))},
 'tw': {'name': TTLocalizer.SuitTightwad,
        'singularname': TTLocalizer.SuitTightwadS,
        'pluralname': TTLocalizer.SuitTightwadP,
        'level': 2,
        'hp': (30,
               40,
               50,
               65,
               80),
        'def': (10,
                15,
                20,
                25,
                30),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (65,
                70,
                75,
                80,
                85),
        'attacks': (('Fired',
                     (5,
                      6,
                      7,
                      8,
                      9),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (75,
                      5,
                      5,
                      5,
                      5)),
                    ('GlowerPower',
                     (5,
                      7,
                      9,
                      12,
                      15),
                     (95,
                      95,
                      95,
                      95,
                      95),
                     (10,
                      15,
                      20,
                      25,
                      30)),
                    ('RazzleDazzle',
                     (4,
                      5,
                      7,
                      9,
                      10),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (5,
                      70,
                      5,
                      5,
                      5)),
                    ('FreezeAssets',
                     (6,
                      9,
                      12,
                      15,
                      18),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (5,
                      5,
                      65,
                      5,
                      30)),
                    ('BounceCheck',
                     (10,
                      12,
                      15,
                      18,
                      20),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (5,
                      5,
                      5,
                      60,
                      30)))},
 'bc': {'name': TTLocalizer.SuitBeanCounter,
        'singularname': TTLocalizer.SuitBeanCounterS,
        'pluralname': TTLocalizer.SuitBeanCounterP,
        'level': 3,
        'hp': (40,
               50,
               65,
               80,
               100),
        'def': (15,
                20,
                25,
                30,
                35),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (70,
                75,
                80,
                82,
                85),
        'attacks': (('Tabulate',
                     (10,
                      12,
                      15,
                      18,
                      20),
                     (95,
                      95,
                      95,
                      95,
                      95),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('Calculate',
                     (6,
                      9,
                      12,
                      15,
                      18),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (25,
                      25,
                      25,
                      25,
                      25)),
                    ('HangUp',
                     (4,
                      6,
                      8,
                      10,
                      12),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (25,
                      25,
                      25,
                      25,
                      25)),
                    ('Audit',
                     (3,
                      4,
                      7,
                      9,
                      13),
                     (95,
                      95,
                      95,
                      95,
                      95),
                     (30,
                      30,
                      30,
                      30,
                      30)))},
 'nc': {'name': TTLocalizer.SuitNumberCruncher,
        'singularname': TTLocalizer.SuitNumberCruncherS,
        'pluralname': TTLocalizer.SuitNumberCruncherP,
        'level': 4,
        'hp': (50,
               65,
               80,
               100,
               125),
        'def': (20,
                25,
                30,
                35,
                40),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (35,
                40,
                45,
                50,
                55),
        'attacks': (('HangUp',
                     (7,
                      10,
                      14,
                      18,
                      22),
                     (60,
                      75,
                      80,
                      85,
                      90),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('Calculate',
                     (10,
                      12,
                      15,
                      18,
                      20),
                     (50,
                      65,
                      70,
                      75,
                      80),
                     (30,
                      30,
                      30,
                      30,
                      30)),
                    ('MarketCrash',
                     (12,
                      13,
                      14,
                      15,
                      16),
                     (60,
                      65,
                      75,
                      80,
                      85),
                     (35,
                      35,
                      35,
                      35,
                      35)),
                    ('PoundKey',
                     (10,
                      12,
                      14,
                      16,
                      18),
                     (50,
                      50,
                      50,
                      50,
                      50),
                     (20,
                      20,
                      20,
                      20,
                      20)))},
 'mb': {'name': TTLocalizer.SuitMoneyBags,
        'singularname': TTLocalizer.SuitMoneyBagsS,
        'pluralname': TTLocalizer.SuitMoneyBagsP,
        'level': 5,
        'hp': (65,
               80,
               100,
               125,
               150),
        'def': (25,
                30,
                35,
                40,
                45),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (35,
                40,
                45,
                50,
                55),
        'attacks': (('PowerTrip',
                     (13,
                      16,
                      18,
                      20,
                      22),
                     (60,
                      75,
                      80,
                      85,
                      90),
                     (30,
                      30,
                      30,
                      30,
                      30)), ('PickPocket',
                     (16,
                      18,
                      20,
                      22,
                      24),
                     (60,
                      65,
                      70,
                      75,
                      80),
                     (45,
                      45,
                      45,
                      45,
                      45)), ('Golf',
                     (13,
                      15,
                      17,
                      19,
                      21),
                     (60,
                      65,
                      75,
                      85,
                      90),
                     (25,
                      25,
                      25,
                      25,
                      25)))},
 'ls': {'name': TTLocalizer.SuitLoanShark,
        'singularname': TTLocalizer.SuitLoanSharkS,
        'pluralname': TTLocalizer.SuitLoanSharkP,
        'level': 6,
        'hp': (80,
               100,
               125,
               150,
               185),
        'def': (30,
                35,
                40,
                45,
                50),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (35,
                40,
                45,
                50,
                55),
        'attacks': (('Bite',
                     (12,
                      15,
                      18,
                      21,
                      24),
                     (60,
                      75,
                      80,
                      85,
                      90),
                     (30,
                      30,
                      30,
                      30,
                      30)),
                    ('PowerTrip',
                     (9,
                      12,
                      15,
                      18,
                      21),
                     (60,
                      70,
                      75,
                      80,
                      90),
                     (35,
                      35,
                      35,
                      35,
                      35)),
                    ('Chomp',
                     (10,
                      12,
                      14,
                      16,
                      18),
                     (55,
                      65,
                      75,
                      85,
                      95),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('ParadigmShift',
                     (17,
                      18,
                      19,
                      20,
                      21),
                     (70,
                      75,
                      80,
                      85,
                      95),
                     (15,
                      15,
                      15,
                      15,
                      15)))},
 'rb': {'name': TTLocalizer.SuitRobberBaron,
        'singularname': TTLocalizer.SuitRobberBaronS,
        'pluralname': TTLocalizer.SuitRobberBaronP,
        'level': 7,
        'hp': (100,
               125,
               150,
               185,
			   235,
			   300,
			   400,
			   500,
               600),
        'def': (35,
                40,
                45,
				55,
				50,
				50,
                50,
				50,
                50),
        'freq': (50,
                 30,
                 15,
				 15,
				 10,
				 5,
				 5,
                 5,
                 5),
        'acc': (30,
                35,
                40,
				45,
				50,
				50,
				50,
                50,
                50),
        'attacks': (('PowerTrip',
                     (15,
                      18,
                      21,
                      24,
					  27,
					  30,
					  32,
					  34,
                      36),
                     (60,
                      65,
                      70,
					  70,
					  70,
					  70,
					  70,
                      75,
                      80),
                     (25,
                      25,
					  25,
					  25,
					  25,
					  25,
                      25,
                      25,
                      25)),
					('PickPocket',
                     (9,
                      15,
                      21,
                      27,
					  33,
					  39,
					  43,
					  47,
                      50),
                     (50,
                      65,
                      70,
                      75,
					  75,
					  75,
					  75,
					  75,
                      80),
                     (25,
                      25,
					  25,
					  25,
					  25,
					  25,
                      25,
                      25,
                      25)),
                    ('CigarSmoke',
                     (18,
                      21,
                      24,
                      27,
					  30,
					  33,
					  35,
					  37,
                      38),
                     (55,
                      65,
                      75,
                      85,
					  85,
					  85,
					  85,
					  85,
                      95),
                     (25,
                      25,
					  25,
					  25,
					  25,
					  25,
                      25,
                      25,
                      25)), 
					('SongAndDance',
                     (12,
                      15,
                      18,
                      21,
					  24,
					  26,
					  28,
					  30,
                      32),
                     (60,
                      65,
                      75,
                      85,
					  85,
					  85,
					  85,
					  85,
                      90),
                     (25,
                      25,
                      25,
					  25,
					  25,
                      25,
					  25,
					  25,
                      25)))},
 'bf': {'name': TTLocalizer.SuitBottomFeeder,
        'singularname': TTLocalizer.SuitBottomFeederS,
        'pluralname': TTLocalizer.SuitBottomFeederP,
        'level': 0,
        'hp': (10,
               20,
               30,
               40,
               50),
        'def': (2,
                5,
                10,
                12,
                15),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (35,
                40,
                45,
                50,
                55),
        'attacks': (('RubberStamp',
                     (4,
                      6,
                      8,
                      10,
                      12),
                     (75,
                      80,
                      85,
                      90,
                      95),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('Shred',
                     (5,
                      7,
                      9,
                      12,
                      15),
                     (50,
                      55,
                      60,
                      65,
                      70),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('Watercooler',
                     (4,
                      6,
                      8,
                      10,
                      12),
                     (95,
                      95,
                      95,
                      95,
                      95),
                     (10,
                      10,
                      10,
                      10,
                      10)),
                    ('PickPocket',
                     (1,
                      2,
                      3,
                      4,
                      5),
                     (60,
                      60,
                      60,
                      60,
                      60),
                     (50,
                      50,
                      50,
                      50,
                      50)))},
 'b': {'name': TTLocalizer.SuitBloodsucker,
       'singularname': TTLocalizer.SuitBloodsuckerS,
       'pluralname': TTLocalizer.SuitBloodsuckerP,
       'level': 1,
       'hp': (20,
              30,
              40,
              50,
              65),
       'def': (5,
               10,
               15,
               20,
               25),
       'freq': (50,
                30,
                10,
                5,
                5),
       'acc': (45,
               50,
               55,
               60,
               65),
       'attacks': (('EvictionNotice',
                    (2,
                     3,
                     4,
                     5,
                     6),
                    (75,
                     75,
                     75,
                     75,
                     75),
                    (20,
                     20,
                     20,
                     20,
                     20)),
				   ('Bite',
                    (6,
                     9,
                     12,
                     15,
                     18),
                    (75,
                     75,
                     75,
                     75,
                     75),
                    (20,
                     20,
                     20,
                     20,
                     20)),
                   ('RedTape',
                    (4,
                     6,
                     8,
                     10,
                     12),
                    (75,
                     75,
                     75,
                     75,
                     75),
                    (20,
                     20,
                     20,
                     20,
                     20)),
                   ('Liquidate',
                    (4,
                     6,
                     8,
                     10,
                     12),
                    (50,
                     60,
                     70,
                     80,
                     90),
                    (50,
                     50,
                     50,
                     50,
                     50)))},
 'dt': {'name': TTLocalizer.SuitDoubleTalker,
        'singularname': TTLocalizer.SuitDoubleTalkerS,
        'pluralname': TTLocalizer.SuitDoubleTalkerP,
        'level': 2,
        'hp': (30,
               40,
               50,
               65,
               80),
        'def': (10,
                15,
                20,
                25,
                30),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (65,
                70,
                75,
                80,
                85),
        'attacks': (('PeckingOrder',
                     (3,
                      4,
                      5,
                      6,
                      7),
                     (50,
                      60,
                      70,
                      80,
                      90),
                     (5,
                      5,
                      5,
                      5,
                      5)),
                    ('BounceCheck',
                     (3,
                      5,
                      7,
                      9,
                      10),
                     (50,
                      60,
                      70,
                      80,
                      90),
                     (5,
                      5,
                      5,
                      5,
                      5)),
                    ('ParadigmShift',
                     (3,
                      6,
                      9,
                      12,
                      15),
                     (50,
                      60,
                      70,
                      80,
                      90),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('DoubleTalk',
                     (9,
                      12,
                      15,
                      18,
                      21),
                     (50,
                      60,
                      70,
                      80,
                      90),
                     (25,
                      25,
                      25,
                      25,
                      25)),
                    ('Schmooze',
                     (11,
                      13,
                      15,
                      17,
                      19),
                     (50,
                      60,
                      70,
                      80,
                      90),
                     (25,
                      25,
                      25,
                      25,
                      25)),
                    ('Rolodex',
                     (10,
                      12,
                      15,
                      18,
                      20),
                     (50,
                      60,
                      70,
                      80,
                      90),
                     (20,
                      20,
                      20,
                      20,
                      20)))},
 'ac': {'name': TTLocalizer.SuitAmbulanceChaser,
        'singularname': TTLocalizer.SuitAmbulanceChaserS,
        'pluralname': TTLocalizer.SuitAmbulanceChaserP,
        'level': 3,
        'hp': (40,
               50,
               65,
               80,
               100),
        'def': (15,
                20,
                25,
                30,
                35),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (65,
                70,
                75,
                80,
                85),
        'attacks': (('EvictionNotice',
                     (10,
                      12,
                      15,
                      18,
                      20),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('PoundKey',
                     (13,
                      14,
                      15,
                      16,
                      17),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (30,
                      30,
                      30,
                      30,
                      30)),
					('ParadigmShift',
                     (6,
                      9,
                      12,
                      15,
                      18),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (30,
                      30,
                      30,
                      30,
                      30)),
                    ('HangUp',
                     (4,
                      6,
                      8,
                      10,
                      12),
                     (75,
                      75,
                      75,
                      75,
                      75),
                     (35,
                      35,
                      35,
                      35,
                      35)))},
 'bs': {'name': TTLocalizer.SuitBackStabber,
        'singularname': TTLocalizer.SuitBackStabberS,
        'pluralname': TTLocalizer.SuitBackStabberP,
        'level': 4,
        'hp': (50,
               65,
               80,
               100,
               125),
        'def': (20,
                25,
                30,
                35,
                40),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (35,
                40,
                45,
                50,
                55),
        'attacks': (('PowerTrip',
                     (12,
                      15,
                      18,
                      21,
                      24),
                     (60,
                      75,
                      80,
                      85,
                      90),
                     (35,
                      35,
                      35,
                      35,
                      35)), ('RestrainingOrder',
                     (9,
                      12,
                      15,
                      18,
                      21),
                     (50,
                      65,
                      70,
                      75,
                      90),
                     (25,
                      25,
                      25,
                      25,
                      25)), ('ParadigmShift',
                     (12,
                      15,
                      18,
                      21,
                      24),
                     (55,
                      65,
                      75,
                      85,
                      95),
                     (15,
                      15,
                      15,
                      15,
                      15)), ('FingerWag',
                     (7,
                      9,
                      11,
                      13,
                      15),
                     (50,
                      55,
                      65,
                      75,
                      80),
                     (25,
                      25,
                      25,
                      25,
                      25)))},
 'sd': {'name': TTLocalizer.SuitSpinDoctor,
        'singularname': TTLocalizer.SuitSpinDoctorS,
        'pluralname': TTLocalizer.SuitSpinDoctorP,
        'level': 5,
        'hp': (70,
               85,
               100,
               125,
               150),
        'def': (25,
                30,
                35,
                40,
                45),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (35,
                40,
                45,
                50,
                55),
        'attacks': (('ParadigmShift',
                     (11,
                      13,
                      15,
                      17,
                      19),
                     (60,
                      75,
                      80,
                      85,
                      90),
                     (30,
                      30,
                      30,
                      30,
                      30)),
                    ('PoundKey',
                     (10,
                      12,
                      14,
                      16,
                      18),
                     (60,
                      65,
                      70,
                      75,
                      80),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('Fired',
                     (12,
                      15,
                      15,
                      18,
                      24),
                     (70,
                      75,
                      80,
                      85,
                      90),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('DoubleTalk',
                     (14,
                      16,
                      18,
                      20,
                      22),
                     (65,
                      75,
                      80,
                      85,
                      90),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('Golf',
                     (9,
                      11,
                      13,
                      15,
                      18),
                     (60,
                      65,
                      75,
                      85,
                      90),
                     (15,
                      15,
                      15,
                      15,
                      15)))},
 'le': {'name': TTLocalizer.SuitLegalEagle,
        'singularname': TTLocalizer.SuitLegalEagleS,
        'pluralname': TTLocalizer.SuitLegalEagleP,
        'level': 6,
        'hp': (80,
               100,
               125,
               150,
               185),
        'def': (30,
                35,
                40,
                45,
                50),
        'freq': (50,
                 30,
                 10,
                 5,
                 5),
        'acc': (35,
                40,
                45,
                50,
                55),
        'attacks': (('Legalese',
                     (11,
                      13,
                      15,
                      17,
                      19),
                     (60,
                      75,
                      80,
                      85,
                      90),
                     (20,
                      20,
                      20,
                      20,
                      20)),
                    ('DoubleTalk',
                     (10,
                      12,
                      14,
                      16,
                      18),
                     (60,
                      70,
                      75,
                      80,
                      90),
                     (15,
                      15,
                      15,
                      15,
                      15)),
                    ('PowerTrip',
                     (17,
                      18,
                      19,
                      20,
                      21),
                     (55,
                      65,
                      75,
                      85,
                      95),
                     (35,
                      35,
                      35,
                      35,
                      35)),
                    ('Schmooze',
                     (15,
                      18,
                      21,
                      24,
                      27),
                     (70,
                      75,
                      80,
                      85,
                      95),
                     (30,
                      30,
                      30,
                      30,
                      30)))},
 'bw': {'name': TTLocalizer.SuitBigWig,
        'singularname': TTLocalizer.SuitBigWigS,
        'pluralname': TTLocalizer.SuitBigWigP,
        'level': 7,
        'hp': (100,
               125,
               150,
               185,
			   235,
			   300,
			   400,
			   500,
			   600,
			   700,
               800),
        'def': (35,
                40,
                45,
                55,
				50,
				50,
				50,
				50,
				50,
				50,
                50),
        'freq': (50,
                 30,
                 10,
				 10,
				 10,
				 10,
				 10,
				 10,
				 10,
                 10,
                 5),
        'acc': (35,
                40,
                45,
                50,
				50,
				50,
				50,
				50,
				50,
				50,
                50),
        'attacks': (('PowerTrip',
                     (10,
                      14,
                      18,
                      21,
					  24,
					  26,
					  28,
					  30,
					  32,
					  34,
                      35),
                     (75,
                      80,
                      85,
                      90,
					  90,
					  90,
					  90,
					  90,
					  90,
					  90,
                      95),
                     (30,
                      30,
                      30,
					  30,
					  30,
					  30,
					  30,
					  30,
					  30,
                      30,
                      30)), 
					('ThrowBook',
                     (15,
                      17,
                      19,
                      21,
					  23,
					  25,
					  27,
					  29,
					  31,
					  33,
                      34),
                     (70,
                      75,
                      85,
					  85,
					  85,
					  85,
					  85,
					  85,
					  85,
                      90,
                      95),
                     (40,
                      40,
					  40,
					  40,
					  40,
					  40,
					  40,
					  40,
                      40,
                      40,
                      40)),
                    ('RazzleDazzle',
                     (16,
                      19,
                      22,
                      25,
					  28,
					  30,
					  32,
					  34,
					  36,
					  38,
                      40),
                     (70,
                      75,
                      85,
					  85,
					  85,
					  85,
					  85,
					  85,
					  85,
                      90,
                      95),
                     (15,
                      15,
					  15,
					  15,
					  15,
					  15,
					  15,
					  15,
                      15,
                      15,
                      15)), 					  
					('CigarSmoke',
                     (22,
                      25,
                      28,
                      31,
					  33,
					  35,
					  37,
					  39,
					  41,
					  43,
                      44),
                     (80,
                      85,
                      85,
					  85,
					  85,
					  85,
					  85,
					  85,
					  85,
                      85,
                      90),
                     (15,
                      15,
					  15,
					  15,
					  15,
					  15,
					  15,
					  15,
                      15,
                      15,
                      15)))}}
ATK_TGT_UNKNOWN = 1
ATK_TGT_SINGLE = 2
ATK_TGT_GROUP = 3
SuitAttacks = {'Audit': ('phone', ATK_TGT_SINGLE),
 'Bite': ('throw-paper', ATK_TGT_SINGLE),
 'BounceCheck': ('throw-paper', ATK_TGT_SINGLE),
 'BrainStorm': ('effort', ATK_TGT_SINGLE),
 'BuzzWord': ('speak', ATK_TGT_SINGLE),
 'Calculate': ('phone', ATK_TGT_SINGLE),
 'Canned': ('throw-paper', ATK_TGT_SINGLE),
 'Chomp': ('throw-paper', ATK_TGT_SINGLE),
 'CigarSmoke': ('cigar-smoke', ATK_TGT_SINGLE),
 'ClipOnTie': ('throw-paper', ATK_TGT_SINGLE),
 'Crunch': ('throw-object', ATK_TGT_SINGLE),
 'Demotion': ('magic1', ATK_TGT_SINGLE),
 'DoubleTalk': ('speak', ATK_TGT_SINGLE),
 'Downsize': ('magic2', ATK_TGT_SINGLE),
 'EvictionNotice': ('throw-paper', ATK_TGT_SINGLE),
 'EvilEye': ('glower', ATK_TGT_SINGLE),
 'Filibuster': ('speak', ATK_TGT_SINGLE),
 'FillWithLead': ('pencil-sharpener', ATK_TGT_SINGLE),
 'FingerWag': ('finger-wag', ATK_TGT_SINGLE),
 'Fired': ('magic2', ATK_TGT_SINGLE),
 'FiveOClockShadow': ('glower', ATK_TGT_SINGLE),
 'FloodTheMarket': ('glower', ATK_TGT_SINGLE),
 'FountainPen': ('pen-squirt', ATK_TGT_SINGLE),
 'FreezeAssets': ('glower', ATK_TGT_SINGLE),
 'Gavel': ('gavel', ATK_TGT_SINGLE),
 'GlowerPower': ('glower', ATK_TGT_SINGLE),
 'GuiltTrip': ('magic1', ATK_TGT_GROUP),
 'HalfWindsor': ('throw-paper', ATK_TGT_SINGLE),
 'HangUp': ('phone', ATK_TGT_SINGLE),
 'HeadShrink': ('magic1', ATK_TGT_SINGLE),
 'HotAir': ('speak', ATK_TGT_SINGLE),
 'Jargon': ('speak', ATK_TGT_SINGLE),
 'Legalese': ('speak', ATK_TGT_SINGLE),
 'Liquidate': ('magic1', ATK_TGT_SINGLE),
 'MarketCrash': ('throw-paper', ATK_TGT_SINGLE),
 'MumboJumbo': ('speak', ATK_TGT_SINGLE),
 'ParadigmShift': ('magic2', ATK_TGT_GROUP),
 'PeckingOrder': ('throw-object', ATK_TGT_SINGLE),
 'PickPocket': ('pickpocket', ATK_TGT_SINGLE),
 'PinkSlip': ('throw-paper', ATK_TGT_SINGLE),
 'PlayHardball': ('throw-paper', ATK_TGT_SINGLE),
 'PoundKey': ('phone', ATK_TGT_SINGLE),
 'PowerTie': ('throw-paper', ATK_TGT_SINGLE),
 'PowerTrip': ('magic1', ATK_TGT_GROUP),
 'Quake': ('quick-jump', ATK_TGT_GROUP),
 'RazzleDazzle': ('smile', ATK_TGT_SINGLE),
 'RedTape': ('throw-object', ATK_TGT_SINGLE),
 'ReOrg': ('magic3', ATK_TGT_SINGLE),
 'RestrainingOrder': ('throw-paper', ATK_TGT_SINGLE),
 'Rolodex': ('roll-o-dex', ATK_TGT_SINGLE),
 'RubberStamp': ('rubber-stamp', ATK_TGT_SINGLE),
 'RubOut': ('hold-eraser', ATK_TGT_SINGLE),
 'Sacked': ('throw-paper', ATK_TGT_SINGLE),
 'SandTrap': ('golf-club-swing', ATK_TGT_SINGLE),
 'Schmooze': ('speak', ATK_TGT_SINGLE),
 'Shake': ('stomp', ATK_TGT_GROUP),
 'Shred': ('shredder', ATK_TGT_SINGLE),
 'Golf': ('golf-club-swing', ATK_TGT_SINGLE),
 'Spin': ('magic3', ATK_TGT_SINGLE),
 'Synergy': ('magic3', ATK_TGT_GROUP),
 'Tabulate': ('phone', ATK_TGT_SINGLE),
 'SongAndDance': ('song-and-dance', ATK_TGT_SINGLE),
 'ThrowBook': ('throw-object', ATK_TGT_SINGLE),
 'Tremor': ('stomp', ATK_TGT_GROUP),
 'Watercooler': ('watercooler', ATK_TGT_SINGLE),
 'Withdrawal': ('magic1', ATK_TGT_SINGLE),
 'WriteOff': ('hold-pencil', ATK_TGT_SINGLE)}
AUDIT = SuitAttacks.keys().index('Audit')
BITE = SuitAttacks.keys().index('Bite')
BOUNCE_CHECK = SuitAttacks.keys().index('BounceCheck')
BRAIN_STORM = SuitAttacks.keys().index('BrainStorm')
BUZZ_WORD = SuitAttacks.keys().index('BuzzWord')
CALCULATE = SuitAttacks.keys().index('Calculate')
CANNED = SuitAttacks.keys().index('Canned')
CHOMP = SuitAttacks.keys().index('Chomp')
CIGAR_SMOKE = SuitAttacks.keys().index('CigarSmoke')
CLIPON_TIE = SuitAttacks.keys().index('ClipOnTie')
CRUNCH = SuitAttacks.keys().index('Crunch')
DEMOTION = SuitAttacks.keys().index('Demotion')
DOWNSIZE = SuitAttacks.keys().index('Downsize')
DOUBLE_TALK = SuitAttacks.keys().index('DoubleTalk')
EVICTION_NOTICE = SuitAttacks.keys().index('EvictionNotice')
EVIL_EYE = SuitAttacks.keys().index('EvilEye')
FILIBUSTER = SuitAttacks.keys().index('Filibuster')
FILL_WITH_LEAD = SuitAttacks.keys().index('FillWithLead')
FINGER_WAG = SuitAttacks.keys().index('FingerWag')
FIRED = SuitAttacks.keys().index('Fired')
FIVE_O_CLOCK_SHADOW = SuitAttacks.keys().index('FiveOClockShadow')
FLOOD_THE_MARKET = SuitAttacks.keys().index('FloodTheMarket')
FOUNTAIN_PEN = SuitAttacks.keys().index('FountainPen')
FREEZE_ASSETS = SuitAttacks.keys().index('FreezeAssets')
GAVEL = SuitAttacks.keys().index('Gavel')
GLOWER_POWER = SuitAttacks.keys().index('GlowerPower')
GUILT_TRIP = SuitAttacks.keys().index('GuiltTrip')
HALF_WINDSOR = SuitAttacks.keys().index('HalfWindsor')
HANG_UP = SuitAttacks.keys().index('HangUp')
HEAD_SHRINK = SuitAttacks.keys().index('HeadShrink')
HOT_AIR = SuitAttacks.keys().index('HotAir')
JARGON = SuitAttacks.keys().index('Jargon')
LEGALESE = SuitAttacks.keys().index('Legalese')
LIQUIDATE = SuitAttacks.keys().index('Liquidate')
MARKET_CRASH = SuitAttacks.keys().index('MarketCrash')
MUMBO_JUMBO = SuitAttacks.keys().index('MumboJumbo')
PARADIGM_SHIFT = SuitAttacks.keys().index('ParadigmShift')
PECKING_ORDER = SuitAttacks.keys().index('PeckingOrder')
PICK_POCKET = SuitAttacks.keys().index('PickPocket')
PINK_SLIP = SuitAttacks.keys().index('PinkSlip')
PLAY_HARDBALL = SuitAttacks.keys().index('PlayHardball')
POUND_KEY = SuitAttacks.keys().index('PoundKey')
POWER_TIE = SuitAttacks.keys().index('PowerTie')
POWER_TRIP = SuitAttacks.keys().index('PowerTrip')
QUAKE = SuitAttacks.keys().index('Quake')
RAZZLE_DAZZLE = SuitAttacks.keys().index('RazzleDazzle')
RED_TAPE = SuitAttacks.keys().index('RedTape')
RE_ORG = SuitAttacks.keys().index('ReOrg')
RESTRAINING_ORDER = SuitAttacks.keys().index('RestrainingOrder')
ROLODEX = SuitAttacks.keys().index('Rolodex')
RUBBER_STAMP = SuitAttacks.keys().index('RubberStamp')
RUB_OUT = SuitAttacks.keys().index('RubOut')
SACKED = SuitAttacks.keys().index('Sacked')
SANDTRAP = SuitAttacks.keys().index('SandTrap')
SCHMOOZE = SuitAttacks.keys().index('Schmooze')
SHAKE = SuitAttacks.keys().index('Shake')
SHRED = SuitAttacks.keys().index('Shred')
SONG_AND_DANCE = SuitAttacks.keys().index('SongAndDance')
SPIN = SuitAttacks.keys().index('Spin')
SYNERGY = SuitAttacks.keys().index('Synergy')
TABULATE = SuitAttacks.keys().index('Tabulate')
TEE_OFF = SuitAttacks.keys().index('Golf')
THROW_BOOK = SuitAttacks.keys().index('ThrowBook')
TREMOR = SuitAttacks.keys().index('Tremor')
WATERCOOLER = SuitAttacks.keys().index('Watercooler')
WITHDRAWAL = SuitAttacks.keys().index('Withdrawal')
WRITE_OFF = SuitAttacks.keys().index('WriteOff')

def getFaceoffTaunt(suitName, doId):
    if suitName in SuitFaceoffTaunts:
        taunts = SuitFaceoffTaunts[suitName]
    else:
        taunts = TTLocalizer.SuitFaceoffDefaultTaunts
    return taunts[doId % len(taunts)]


SuitFaceoffTaunts = OTPLocalizer.SuitFaceoffTaunts

def getAttackTauntIndexFromIndex(suit, attackIndex):
    adict = getSuitAttack(suit.getStyleName(), suit.getLevel(), attackIndex)
    return getAttackTauntIndex(adict['name'])


def getAttackTauntIndex(attackName):
    if attackName in SuitAttackTaunts:
        taunts = SuitAttackTaunts[attackName]
        return random.randint(0, len(taunts) - 1)
    else:
        return 1


def getAttackTaunt(attackName, index = None):
    if attackName in SuitAttackTaunts:
        taunts = SuitAttackTaunts[attackName]
    else:
        taunts = TTLocalizer.SuitAttackDefaultTaunts
    if index != None:
        if index >= len(taunts):
            notify.warning('index exceeds length of taunts list in getAttackTaunt')
            return TTLocalizer.SuitAttackDefaultTaunts[0]
        return taunts[index]
    else:
        return random.choice(taunts)
    return


SuitAttackTaunts = TTLocalizer.SuitAttackTaunts
DisabledAttacks = ('Gavel',  'SandTrap', 'FloodTheMarket', 'FiveOClockShadow')

def getAttacksByType(attributes):
    groupAttacks = []
    singleAttacks = []

    for attack in sorted(attributes['attacks'], key=lambda x: x[0]):
        if attack[0] in DisabledAttacks:
            continue
        if SuitAttacks[attack[0]][1] == ATK_TGT_GROUP:
            groupAttacks.append(attack)
        else:
            singleAttacks.append(attack)
    
    return groupAttacks, singleAttacks