daemon:
    name: Production Cluster

general:
    eventlogger: 25.57.238.215:7198
    dc_files:
        - ../dclass/stride.dc

messagedirector:
    bind: 25.57.238.215:7100

roles:
    - type: stateserver
      control: 4002

    - type: database
      control: 4003
      generate:
        min: 100000000
        max: 399999999
      backend:
        type: mongodb
        server: mongodb://25.57.238.215:27017/stride

    - type: dbss
      database: 4003
      ranges:
        - min: 100000000
          max: 399999999
